klips-project/klips-sdi

.github/workflows/deploy.yml, docker-compose.yml
Add GitHub Action that automatically builds a Docker image of `geoserver-init`
At one point it might be better to move `geoserver-init` to another repo like described in #7
=> Docker image

.github/workflows/deploy.yml
* fixes #13
* add a timestamp tag to the created Docker image
* shall make it easier to try former images
* an alternative would be to use a git commit hash as tag. 
* pro: easy link to respective commit in code
* con: finding out which tag is later or earlier does not work so easy as with timestamps
=> Add timestamp to docker image

workflows/publish-imagemosaic.json
This adds a simple job example for a) downloading a geotif and b) publish it to an existing imagemosaic coverage store.
@weskamm please check.
=> Add workflow json for publish an imagemosaic

docker-compose.yml
As the title says, the data dir is required by the API, so we add it.
=> Add geoserver data dir as volume to API as its required now

docker-compose.yml, workflows/create-imagemosaic-datastore.json, workflows/publish-imagemosaic.json
This updates the `docker-compose.yml` file by adding the `geoserver-create-imagemosaic-datastore` worker.  
Also adapts the respective job jsons.  
@weskamm @chrismayer what do you think?
=> Add create-imagemosaic-datastore worker

docker-compose.yml, geoserver-init/000_change_auth.js, geoserver-init/package-lock.json, geoserver-init/package.json, worker/rollback-handler/index.js
- Upgrade and cleanup dependencies
- on a clean setup the geoserver-init script failed, because the newly created user was not availble yet. The reason is probably the heavy load of the workers requesting geoserver and delaying the process of creating  new user. We now add 10 seconds time to wait to ensure the new user is acutally registered
=> geoserver-init: Upgrade dependencies and BugFix

workflows/create-imagemosaic-datastore.json, workflows/publish-imagemosaic.json
After an update of the `create-imagemosaic-datastore` worker, these job-jsons needs to be updated.
@JakobMiksch
=> Update imagemosaic workflows

pygeoapi/Dockerfile, pygeoapi/README.md, pygeoapi/processes/algorithms/location_info.py, pygeoapi/processes/algorithms/zonal_stats.sh, pygeoapi/processes/location_info_rasterstats.py, pygeoapi/processes/zonal_statistics_gdal.py, pygeoapi/pygeoapi-config.yml
- adds a process to query the information of one location in a COG using the Python library [rasterstats](https://pythonhosted.org/rasterstats/index.html)
- `rasterstats` is based on GDAL/OGR. It can query COGs and **only** requests the necessary information. It does **not** download the whole file to perform analysis
- some minor fixes and docs
- the algorithm for the location info is in a separate python to make it possible to run it without pygeoapi (useful for development)
- follow-up PR is https://github.com/klips-project/klips-sdi/pull/87
- Upgrade pygeoapi to 0.13.0 - fixes #88
=> pygeoapi: add locationinfo using rasterstats

pygeoapi/processes/zonal_statistics_grass.py
This should fix the import of `standalone_grass_zonal` script.  
@weskamm @JakobMiksch please check.
=> Fix: pygeoapi import for standalone grass script

klips-api/src/config/job-conf.json
- before it was 10MB
- should fix recent error messages from server
=> Increase limit filesize GeoTIFF to 20MB

.env.example, docker-compose.yml
Make use of `container_name` variable in docker compose file. https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name  
Why? Increase readability with large amounts of containers.
Possible drawback, no scaling, because name must be unique.  
@chrismayer @JakobMiksch @weskamm
=> Docker compse file: Use container_name

.env.example, docker-compose.yml, pygeoapi/pygeoapi-config.yml
This uses an .env variable to set the base url in `pygeoapi-config.yaml`.  
Needs to be adapted in production, e.g. `https://klips-dev.terrestris.de/pygeoapi`.  
@chrismayer @weskamm @JakobMiksch
=> Use variable for pygeoapi baseurl

.env.example, docker-compose.yml
Move compose setting to env variable, to prevent unnecessary git diffs on the server
=> Move compose setting to env variable

pygeoapi/Dockerfile
- adds missing line to install gdal and grass
=> pygeoapi docker: fix failing build

.env.example, docker-compose.yml, geoserver-init/logger.js, klips-api/src/logger/index.ts, worker/error-handler/logger.js, worker/rollback-handler/logger.js
- logging level of "stream" that is shown in docker logs can be configured. For example it might be useful to set it to INFO in production enviroments
- logging level for log file will always be DEBUG (the lowest) to be able to understand errors later on
=> Separate logging level for stdout

easy-to-use-api/klips-chart-api/Dockerfile
Add Dockerfile (12mb) for chart-api.
please note @weskamm @chrismayer @sdobbert
=> Add klips-chart-api Dockerfile

easy-to-use-api/klips-chart-api/src/components/Chart/index.ts, easy-to-use-api/klips-chart-api/src/types/index.ts, easy-to-use-api/klips-chart-api/src/util/Chart.ts
- Improve types import for echart
- improve modular import for echart
- reduce bundle size by ~30% (still 700kb!, ideas?)
```
vite v4.3.9 building for production...
✓ 641 modules transformed.
dist/index.html                   0.42 kB │ gzip:   0.29 kB
dist/assets/index-c0f34f63.css    0.19 kB │ gzip:   0.16 kB
dist/assets/index-17c20c83.js   722.96 kB │ gzip: 233.41 kB
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 5.55s
```
@weskamm @chrismayer @sdobbert please check.
=> Improve chart-api echarts bundle

easy-to-use-api/klips-chart-api/src/util/Chart.ts
Parsefloat is already done at other point (when creating series for chart).
direct merge, please note @sdobbert
=> Minor fix chart data formatting

nginx/default.conf
Gzip has been enabled on the native installed ~docker~ nginx on the server to have effect. Can be deleted here.
@chrismayer @weskamm @sdobbert
=> Remove gzip settings in docker nginx

docker-compose.localdev.yml, docker-compose.yml, klips-api/src/converter.ts
The `dataset-rotation` worker manages to delete the oldest dataset, when new data arrives.   
Dependent on: https://github.com/klips-project/rabbitmq-worker/pull/157  
Adapts the job list for the klips-api.
@chrismayer @sdobbert @weskamm
=> Add dataset-rotation worker

easy-to-use-api/klips-chart-api/src/components/Chart/index.ts, easy-to-use-api/klips-chart-api/src/constants/index.ts, easy-to-use-api/klips-chart-api/src/types/index.ts, easy-to-use-api/klips-chart-api/src/util/Chart.ts, easy-to-use-api/klips-chart-api/src/util/Config.ts
Checks if point for chart api is within the correct boundary box (Dresden or Langenfeld) and gives a console error if not.
Two pervious commits included here are also included in previous pr: https://github.com/klips-project/klips-sdi/pull/181 
They can be deleted after this pr has been merged.
=> Geometry check

easy-to-use-api/klips-chart-api/content.json, easy-to-use-api/klips-chart-api/src/components/Chart/index.ts, easy-to-use-api/klips-chart-api/src/components/Docs/index.ts, easy-to-use-api/klips-chart-api/src/constants/index.ts, easy-to-use-api/klips-chart-api/src/types/index.ts, easy-to-use-api/klips-chart-api/src/util/Chart.ts
Adds a parameter "band" to the chart url to select which band (physical temperature, perceived temperature, or temperature difference) is displayed first in the chart.
Options are physical, perceived, difference, and compare with the compare option showing physical temperature and either perceived or temperature difference in one graph for direct comparison.
Default is perceived temperature.
example: /?region=dresden&geomwkt=POINT(13.77509%2051.06778)&threshold=22.5&band=compare
@hblitza @chrismayer
=> Add band parameter to chart url

easy-to-use-api/klips-chart-api/package-lock.json, easy-to-use-api/klips-chart-api/package.json, easy-to-use-api/klips-chart-api/src/components/Chart/index.ts, easy-to-use-api/klips-chart-api/src/constants/index.ts, easy-to-use-api/klips-chart-api/src/service/ogc-api-service/index.ts, easy-to-use-api/klips-chart-api/src/types/index.ts, easy-to-use-api/klips-chart-api/src/util/Chart.ts, easy-to-use-api/klips-chart-api/src/util/Config.ts
Adapts the KLIPS-Chart-API for an Input-Polygon, which is specified in the URL. Mean values are created using zonal statistics (zonal_statistics_time_rasterstats).
Example URL:
/?region=dresden&geomwkt={"coordinates":%20[[[13.72242,%2051.04242],[13.72242,%2051.06019],[13.74525,%2051.06019],[13.74525,%2051.04242],[13.72242,%2051.04242]]],"type":%20"Polygon"}&threshold=25 
or for WKT-Input:
/?region=dresden&geomwkt=POLYGON((13.72242%2051.04242,%2013.72242%2051.06019,%2013.74525%2051.06019,%2013.74525%2051.04242,%2013.72242%2051.04242))&threshold=25&band=physical
=> Create chart for polygon (mean values)

.github/workflows/test-pygeoapi.yml, pygeoapi/Dockerfile, pygeoapi/dev_scripts/default.conf, pygeoapi/processes/algorithms/timelapse_video.py
This should fix the failing pygeoapi lint and test pipeline, cf. https://github.com/klips-project/klips-sdi/actions/workflows/test-pygeoapi.yml  
Issues fixed:
- do not start docker-compose, use `docker run` to only run the test-nginx container
- fix pylint errors
@chrismayer @FritzHoing @sdobbert please note
=> repair pygeoapi test

demonstrator-ogc-services/klips-wmts-demo/src/App.less, demonstrator-ogc-services/klips-wmts-demo/src/App.tsx, demonstrator-ogc-services/klips-wmts-demo/src/components/BasicLayerSelector/index.less, demonstrator-ogc-services/klips-wmts-slider/src/App.less, demonstrator-ogc-services/klips-wmts-slider/src/App.tsx, demonstrator-ogc-services/klips-wmts-slider/src/components/BasicSwipe/index.tsx, demonstrator-ogc-services/klips-wmts-slider/src/index.less
Unifies the style of the WMTS-demonstrators (klips-wmts-slider, klips-wmts-simulation, and klips-wmts-demo).
Legends and optional windows are now shown on the right, leaving more room for the map:
=> demonstrator styling

docker-compose.yml
This will be needed when creating the countour lines within the geoserver. It is already installed on the staging server.
=> feat: adds geoserver extention

klips-api/src/converter.ts
Moves reclassify-geotiff worker job to the end, as the job is taking longest and is potentially interfering with the following jobs.
=> fix: job order

docker-compose.localdev.yml, docker-compose.yml
12g xms should be enough for a productive system.
The Flag -XX:+UseG1GC is added as a garbage collector, since it is recommended to be added under continuous load and heap sizes of 6GB or more.
Please review @sdobbert
=> fix: allocates more xmx and garbage collection
