- docker-compose.yml
Update GeoServer to latest release
> Update GeoServer to latest release

- README.md
move readme snippet to correct repo
> README: move instructions for CLI usage

- docker-compose.yml
- workflows/publish-geotiff-with-validator.json
> Add geotiff-validator to SDI

- docker-compose.yml
- Upgrade RabbitMQ to `3.10`
- just a minor release. I tested it quickly and it seems to work
> Upgrade RabbitMQ to `3.10`

- .gitignore
- README.md
- docker-compose.yml
- klips-api-config-example/basic-auth-users.json
- klips-api-config-example/schema-geotiff-upload.json
As discussed, this adds the api docker image to the compose file.
@JakobMiksch @hblitza please review
> Add Klips API to docker-compose setup

- geoserver-init/000_change_auth.js
- geoserver-init/010_create_workspace.js
> Fix geoserver-node-client

- docker-compose.yml
- workflows/publish-geotiff-with-validator.json
- workflows/publish-geotiff.json
image has been renamed long time ago...
@hblitza @JakobMiksch please review
> Update the file downloader image

- docker-compose.yml
- follow up of #31
- fixes #11
> Change name of download-worker Part 2

- docker-compose.yml
- worker/error-handler/README.md
- worker/error-handler/index.js
- enebles dev mode for error handler that prevents sending messages.
> Set dev mode for error messages

- .github/workflows/deploy.yml
- docker-compose.yml
> CI: build docker image for error handler

- docker-compose.yml
- worker/error-handler/index.js
- worker/rollback-handler/Dockerfile
- worker/rollback-handler/index.js
- worker/rollback-handler/package-lock.json
- worker/rollback-handler/package.json
- workflows/rollback-test.json
Make sure you have set the `MATTERMOST_HOOK_URL` in your env file before testing this!
This adds a rollback handler which deletes datastores in geoserver and files that have been downloaded when a job fails
@JakobMiksch @hblitza please review
> Adding rollback handler

- worker/error-handler/Dockerfile
- worker/error-handler/start-worker.sh
- worker/error-handler/wait-for.sh
Make error handler wait for RabbitMQ
> Make error handler wait for RabbitMQ

- worker/rollback-handler/Dockerfile
- worker/rollback-handler/start-worker.sh
- worker/rollback-handler/wait-for.sh
Make rollback-worker wait for RabbitMQ
> Make rollback-worker wait for RabbitMQ

- .github/workflows/deploy.yml
- docker-compose.yml
> Build rollback image via CI

- worker/rollback-handler/index.js
- workflows/rollback-test-imagemosaic.json
- workflows/rollback-test.json
This adds the rollback case for imagemosaic:
- delete single granule from coverage store (rather than deleting the while coverage store).
- some refactoring
@weskamm @JakobMiksch please review!
> Init rollback for imagemosaic

- workflows/publish-geotiff-with-validator-error.json
- workflows/publish-geotiff-with-validator.json
- workflows/publish-geotiff.json
- workflows/rollback-test.json
This fixes all workflows as volume mappings have changed.
@JakobMiksch @hblitza please review
> Fix workflows by using correct compose volume path

- docker-compose.yml
> Use correct image for datastore worker

- worker/error-handler/index.js
- worker/rollback-handler/index.js
Since ES6 there is the `includes()` method that can be used to check if an item is present in an array.
> Replace`indexOf()` with `includes()`

- docker-compose.yml
Docker-Compose: restart services
> Docker-Compose: restart services

- README.md
An instruction how to to develop worker more efficiently.
> README: hint how to develop workers

- geoserver-init/010_create_workspace.js
Create workspaces dresden and langenfeld initially
> Create workspaces dresden and langenfeld initially

- .env.example
- docker-compose.yml
needed for https://github.com/klips-project/rabbitmq-worker/pull/104
> Add GEOSERVER_DATA_DIR to docker-compose

- klips-api-config-example/job-conf.json
follow up of https://github.com/klips-project/klips-api/pull/26
> Add config for jobs

- pygeoapi/processes/zonal_statistics_gdal.py
- pygeoapi/processes/zonal_statistics_grass.py
- add some documentation
- use r.external for the GRASS script
- remove requirement of name for the GDAL script
Please review @JakobMiksch @hwbllmnn
> Update zonal statistic processes

- docker-compose.yml
Update GeoServer to 2.21.1 and skip demo data
> Update GeoServer to 2.21.1 and skip demo data

- klips-api-config-example/job-conf.json
- klips-api-config-example/schema-geotiff-upload.json
- klips-api-config-example/swagger.yaml
- Update KLIPS API config files
- merge after https://github.com/klips-project/klips-api/pull/40
> Update KLIPS API config files

- .github/workflows/deploy.yml
- docker-compose.dev.yml
- docker-compose.yml
- geoserver/Dockerfile
> Add geoserver dockerfile to implement cog ext

- geoserver/Dockerfile
> GeoServer Dockerfile Fix

- workflows/add-single-cog.json
- workflows/create-cog-datastore.json
fixes the sample workflow to run out-of-the-box
> Adapt sample workflows

- docker-compose.yml
Remove not needed WPS extension
> Remove not needed WPS extension

- pygeoapi/processes/location_info_rasterstats.py
- pygeoapi/processes/location_info_time_rasterstats.py
- pygeoapi/processes/zonal_statistics_rasterstats.py
- pygeoapi/processes/zonal_statistics_time_rasterstats.py
this fixes the naming of the crs param
@hblitza @JakobMiksch please review
> Fixup crs param

- .gitignore
- docker-compose.yml
- geoserver-init/000_change_auth.js
- geoserver-init/010_setup_geoserver.js
- geoserver-init/Dockerfile
- geoserver-init/logger.js
- geoserver-init/package-lock.json
- geoserver-init/package.json
- klips-api/Dockerfile
- klips-api/src/index.ts
- klips-api/src/logger/index.ts
- worker/error-handler/Dockerfile
- worker/error-handler/index.js
- worker/error-handler/logger.js
- worker/error-handler/package-lock.json
- worker/error-handler/package.json
- worker/rollback-handler/Dockerfile
- worker/rollback-handler/index.js
- worker/rollback-handler/logger.js
- worker/rollback-handler/package-lock.json
- worker/rollback-handler/package.json
- adds pino logging to
- 'geoserver-init'
- 'rollback-handler'
- 'error-handler'
- 'klips-api'
- connected to https://github.com/klips-project/rabbitmq-worker/pull/140
> Pino for all workers

- docker-compose.yml
- geoserver-init/Dockerfile
- geoserver-init/logger.js
- klips-api/Dockerfile
- klips-api/src/logger/index.ts
- worker/error-handler/logger.js
- worker/rollback-handler/logger.js
same as https://github.com/klips-project/rabbitmq-worker/pull/141
> Add worker property within pino

- docker-compose.yml
To avoid struggle with native installed nginx on the server.  
@chrismayer @JakobMiksch @weskamm
> Adapt nginx port to 81

- demonstrator/ogc-api-processes/main.js
@JakobMiksch @hblitza please review
> Fix file pathes in demonstrator

- worker/error-handler/Dockerfile
- worker/rollback-handler/Dockerfile
- adds a fixed version to Node docker image 
- fixes https://github.com/klips-project/klips-sdi/issues/79
> Set fixed versions for docker image

- docker-compose.yml
GeoServer install importer extension
> GeoServer install importer extension

- README.md
- workflows/add-single-cog.json
minor adaptation in the example workflows
> Adapt example workflow to run with cronjob

- configs-example/swagger.yaml
- adds missing parameter to example
- removes not needed comments
- update sample URL
> Update swagger yaml

- demonstrator/ogc-api-processes/main.js
- non-functional!
- some documentation of the demonstrator
- variable renaming
- remove quotes where not needed
> Documentation web demonstrator

- workflows/add-single-cog.json
> Adapt sample workflow

- configs-example/job-conf.json
- configs-example/schema-geotiff-upload.json
- configs-example/swagger.yaml
- klips-api/example_requests/send-geotiff-dresden.json
- klips-api/example_requests/send-geotiff-langenfeld.json
- klips-api/src/converter.ts
- klips-api/src/types/index.ts
- removes the "type" property from the JSON that is sent to the API
> Remove "type" from API request JSON

- klips-api/src/converter.ts
- adaptations for https://github.com/klips-project/rabbitmq-worker/pull/150
> geotiff-validator: refactor

- docker-compose.yml
> Disable GeoServer CSRF protection

- pygeoapi/Dockerfile
- pygeoapi/processes/algorithms/grass_algorithms.py
- pygeoapi/processes/zonal_statistics_grass.py
This addresses the GRASS script to calculate raster stats:
- fix grass modules import to make it working it again  
- add custom crs
- refactor input params (geojson, inputcrs)
- add check for cog url
@weskamm @JakobMiksch
> Pygeoapi: GRASS script add custom crs support and overall fixes

- LICENSE
- geoserver-init/package.json
> Change license to BSD2-clause

- .env.example
- docker-compose.yml
- geoserver-init/000_change_auth.js
- geoserver-init/010_setup_geoserver.js
- geoserver-init/logger.js
- klips-api/src/converter.ts
- klips-api/src/logger/index.ts
- worker/error-handler/logger.js
- worker/rollback-handler/logger.js
- based on #145 
- see the diff in this commit: f6aed70128a406d16771884cc92f278150da6ca1
- improved logging output to hide all unnecessary information in INFO level and only show it in DEBUG level
- this creates a much more understandable output in production scenarios
- the DEBUG statements can still be viewed in the log files
> Logging: move details to DEBUG level

- geoserver-init/010_setup_geoserver.js
- add function to automatically add contact information to GeoServer
> Add contact information to GeoServer

- .github/workflows/test-pygeoapi.yml
- pygeoapi/.flake8
- pygeoapi/dev_scripts/lint.sh
- pygeoapi/processes/algorithms/grass_algorithms.py
- pygeoapi/processes/algorithms/rasterstats_algorithms.py
- pygeoapi/processes/algorithms/test_rasterstats_algorithms.py
- pygeoapi/processes/algorithms/test_util.py
- pygeoapi/processes/algorithms/util/__init__.py
- pygeoapi/processes/location_info_rasterstats.py
- pygeoapi/processes/location_info_time_rasterstats.py
- pygeoapi/processes/zonal_statistics_grass.py
- pygeoapi/processes/zonal_statistics_rasterstats.py
- pygeoapi/processes/zonal_statistics_time_rasterstats.py
- based on #148 
- adapts formatting to [black](https://black.readthedocs.io/en/stable/index.html)
- adapts CI
> pygeoapi: lint with black formatter

- demonstrator/ogc-api-processes/main.js
- pygeoapi/Dockerfile
- pygeoapi/processes/algorithms/grass_algorithms.py
- pygeoapi/processes/zonal_statistics_grass.py
This fixes the grass rasterstats process by:
- adding new input param for crs
- using first band of  raster
- update shapely to use `from_geojson` function
- cf. https://github.com/geopython/pygeoapi/pull/1072
Use multiple bands /selected bands must be fixed in follow up pr.
@weskamm @chrismayer
> Fix grass rasterstats process

- README.md
see title
@hblitza please review
> fix: add license info in README

- klips-api/package-lock.json
- klips-api/package.json
This updates outdated libs to latest version. Checked and tested, works fine after update.
fyi @sdobbert @chrismayer
> Klips-API Update outdated libs

- .gitignore
- klips-widget-api/.editorconfig
- klips-widget-api/.eslintignore
- klips-widget-api/.eslintrc.cjs
- klips-widget-api/index.html
- klips-widget-api/package-lock.json
- klips-widget-api/package.json
- klips-widget-api/src/components/Chart/index.ts
- klips-widget-api/src/constants/index.ts
- klips-widget-api/src/main.ts
- klips-widget-api/src/style.css
- klips-widget-api/src/types/index.ts
- klips-widget-api/src/util/Config.ts
- klips-widget-api/src/util/Url.ts
- klips-widget-api/src/vite-env.d.ts
- klips-widget-api/tsconfig.json
This initializes the widget api within the klips-sdi repo.  
It is a simple web application only using vite, typescript and echarts and parses the url location (search params or pathnames) to create a chart.
In follow-up pr:
- tests (!)
- connect klips-api to get data
- validation of parameters (e.g. geometry checking)
@chrismayer @sdobbert please check
> Init widget api

- easy-to-use-api/klips-timelapse-video-api/.editorconfig
- easy-to-use-api/klips-timelapse-video-api/.eslintignore
- easy-to-use-api/klips-timelapse-video-api/.eslintrc.cjs
- easy-to-use-api/klips-timelapse-video-api/.gitignore
- easy-to-use-api/klips-timelapse-video-api/README.md
- easy-to-use-api/klips-timelapse-video-api/__mocks__/client.js
- easy-to-use-api/klips-timelapse-video-api/__mocks__/styleMock.js
- easy-to-use-api/klips-timelapse-video-api/index.html
- easy-to-use-api/klips-timelapse-video-api/jest-setup.ts
- easy-to-use-api/klips-timelapse-video-api/jest.config.ts
- easy-to-use-api/klips-timelapse-video-api/package-lock.json
- easy-to-use-api/klips-timelapse-video-api/package.json
- easy-to-use-api/klips-timelapse-video-api/src/main.ts
- easy-to-use-api/klips-timelapse-video-api/src/style.css
- easy-to-use-api/klips-timelapse-video-api/src/types/index.ts
- easy-to-use-api/klips-timelapse-video-api/src/util/Config.ts
- easy-to-use-api/klips-timelapse-video-api/src/util/Url.ts
- easy-to-use-api/klips-timelapse-video-api/tsconfig.json
This adds the easy-to-use-api for the timelapse-video process.
By calling an URL like 
http://localhost:5173/?region=dresden&area-of-interest={%22coordinates%22:%20[[[13.72242,%2051.04242],[13.72242,%2051.06019],[13.74525,%2051.06019],[13.74525,%2051.04242],[13.72242,%2051.04242]]],%22type%22:%20%22Polygon%22}&output=mp4&title=Test
it generates a HTML page with loadmask and videoplayer that shows the requested video:
TODO: Handle output and region parameter correctly after final discussion
> Add easy-to-use-api for timelapse video

- pygeoapi/Dockerfile
- pygeoapi/processes/algorithms/timelapse_video.py
This adds the geometry provided by the user to the resulting video ontop for reference.
The dateTime in the lower corner has been formatted:
https://github.com/klips-project/klips-sdi/assets/1381363/22c78bd7-ee36-48d9-bf6f-e1487adbc381
> Timelapse enhancements

- .github/workflows/deploy.yml
- docker-compose.yml
Add docker nginx service to serve easy-to-use apis. Starting with `chart`.  
Add github action to run build for the chart api.  
@weskamm @chrismayer @sdobbert
> Docker service easy-to-use-api

- easy-to-use-api/klips-chart-api/src/constants/index.ts
:1st_place_medal:  (copy paste error)...
> Chart API Use correct process endpoint

- nginx/default.conf
Moves location from native intalled nginx to docker config.
> Add nginx location for klips-api

- easy-to-use-api/klips-chart-api/src/components/Chart/index.ts
- easy-to-use-api/klips-chart-api/src/types/index.ts
- easy-to-use-api/klips-chart-api/src/util/Chart.ts
1. use one decimal for temperature data
2. fix correct band selection in formatChartData function
@chrismayer @weskamm @sdobbert :pray:
> feat: chart api fix band values

- easy-to-use-api/klips-chart-api/src/util/Chart.ts
Adds the KLIPS-Logo to the chart and rounds the input data to 1 digit.
> add klips logo and link to chart

- easy-to-use-api/klips-chart-api/src/constants/index.ts
> fix unneeded import

- docker-compose.localdev.yml
- docker-compose.yml
- klips-api/src/converter.ts
Creates new archiving worker.
See: https://github.com/klips-project/rabbitmq-worker/pull/161
@hblitza @chrismayer
> Archive worker

- klips-api/src/converter.ts
Follow-up fix, corrects the inputs for the dataset-rotation worker.
fyi @chrismayer @sdobbert
> fix inputs for dataset-rotation worker

- easy-to-use-api/klips-chart-api/src/components/Chart/index.ts
- easy-to-use-api/klips-chart-api/src/util/Config.ts
Some minor fixes for the Chart-API:
- Fixes threshold line, which is now displayed in the chart
- moves toolbox to fix overlapping title
@chrismayer @hblitza
> Chart-API: Minor style fixes

- easy-to-use-api/klips-chart-api/src/components/Chart/index.spec.ts
- easy-to-use-api/klips-chart-api/src/util/Config.ts
- pygeoapi/Dockerfile
A few minor fixes for pygeoapi and klips-chart-api to run properly.
> Minor fixes for pygeoapi and chart-api

- easy-to-use-api/klips-chart-api/README.md
- easy-to-use-api/klips-chart-api/package-lock.json
- easy-to-use-api/klips-chart-api/package.json
- update vite
- adjusting URL in Readme
> Minor fixes

- .github/workflows/deploy.yml
> ci: adds workflow for building image

- .github/workflows/deploy.yml
> Update deploy step

- .github/workflows/deploy.yml
- deploy.sh
Co authored by @FritzHoing , will merge directly
> Fix deploy ci, add sh script deploy

- .github/dependabot.yml
TODO: handle multiple directories, e.g using groups.
@chrismayer
> init dependabot

- easy-to-use-api/klips-chart-api/package-lock.json
- easy-to-use-api/klips-chart-api/package.json
This fix the npm dependencies. Accidentally upgraded by dependabot.
> downgrade of eslint plugin to v5

- easy-to-use-api/klips-url-generator/src/components/DrawGeometry/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectBand/index.tsx
- easy-to-use-api/klips-url-generator/src/style.css
- implements translation
- minor css fix
> fix: implement translation

- .github/workflows/build.yml
> Change build trigger to manual

- easy-to-use-api/klips-chart-api/package-lock.json
- easy-to-use-api/klips-chart-api/package.json
- easy-to-use-api/klips-chart-api/src/components/Chart/index.ts
- easy-to-use-api/klips-chart-api/src/constants/index.ts
- easy-to-use-api/klips-chart-api/src/main.ts
> fix: import dotenv to access variables

- easy-to-use-api/klips-chart-api/.eslintrc.cjs
- easy-to-use-api/klips-chart-api/src/components/Docs/index.ts
- easy-to-use-api/klips-chart-api/src/main.ts
- easy-to-use-api/klips-chart-api/src/service/ogc-api-service/index.ts
- easy-to-use-api/klips-chart-api/src/types/index.ts
- easy-to-use-api/klips-chart-api/src/util/Chart.ts
- easy-to-use-api/klips-chart-api/src/util/Config.ts
Title says it all
please review @sdobbert
> lint: fix linting

- easy-to-use-api/klips-chart-api/src/constants/index.ts
> fix: make environment variables accessible

- easy-to-use-api/klips-chart-api/index.html
> fix: change to relative path

- deploy.sh
and create missing .env file out of .env.examples
> fix: restart docker

- easy-to-use-api/klips-chart-api/src/constants/index.ts
- easy-to-use-api/klips-chart-api/vite.config.js
> fix: minor ts fix

- easy-to-use-api/klips-url-generator/src/components/ChartComponent/index.tsx
- easy-to-use-api/klips-url-generator/src/components/VideoComponent/index.tsx
- easy-to-use-api/klips-url-generator/src/components/WarningComponent/index.tsx
> fix: minor fix url generator

- easy-to-use-api/klips-url-generator/src/components/ChartComponent/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectBand/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectRegion/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectThreshold/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectWidget/index.tsx
- easy-to-use-api/klips-url-generator/src/components/VideoComponent/SelectVideoFormat/index.tsx
- easy-to-use-api/klips-url-generator/src/components/VideoComponent/WritePersonalTitle/index.tsx
- easy-to-use-api/klips-url-generator/src/components/WarningComponent/index.tsx
- easy-to-use-api/klips-url-generator/src/style.css
Some minor changes to the Styling of the KLIPS URL-Generator:
- make URL-output window a TextArea
- change color of no-input messages
- remove 'compare'-Band option for the warning widget
> minor style fixes

- easy-to-use-api/klips-timelapse-video-api/.env.example
- easy-to-use-api/klips-timelapse-video-api/src/main.ts
- easy-to-use-api/klips-url-generator/src/components/VideoComponent/index.tsx
title says all.
coauthored by @FritzHoing
> fix execution url

- easy-to-use-api/klips-chart-api/index.html
- easy-to-use-api/klips-chart-api/src/main.ts
- easy-to-use-api/klips-chart-api/src/service/ogc-api-service/index.ts
- easy-to-use-api/klips-chart-api/src/style.css
- easy-to-use-api/klips-chart-api/src/util/Config.ts
Some minor fixes for the KLIPS Chart API:
- add loading mask
> Minor fixes for Chart API

- easy-to-use-api/klips-url-generator/src/App.tsx
- easy-to-use-api/klips-url-generator/src/components/ChartComponent/index.tsx
- easy-to-use-api/klips-url-generator/src/components/DrawGeometry/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectBand/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectRegion/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectThreshold/index.tsx
- easy-to-use-api/klips-url-generator/src/components/SelectWidget/index.tsx
- easy-to-use-api/klips-url-generator/src/components/VideoComponent/SelectVideoFormat/index.tsx
- easy-to-use-api/klips-url-generator/src/components/VideoComponent/WritePersonalTitle/index.tsx
- easy-to-use-api/klips-url-generator/src/components/VideoComponent/index.tsx
- easy-to-use-api/klips-url-generator/src/components/WarningComponent/index.tsx
- easy-to-use-api/klips-url-generator/src/constants/index.ts
- easy-to-use-api/klips-url-generator/src/style.css
Fixes multiple issues:
- Dresden is set as default region
- sets default band value
- sets default video-type value
- adds a mailto when URL is generated
- adds a open in new tab button
- adds iframe example
- deletes features and geometry from draw layer when widget is changed
- translates several buttons
- adds a point when drawing polygons
- several ui improvements
Please review @hblitza & @sdobbert
> Url generator feedback

- easy-to-use-api/klips-url-generator/src/components/WarningComponent/index.tsx
> fix url for warning in url generator

- docker-compose.yml
> add port to postgres

- demonstrator-ogc-services/klips-wmts-slider/src/App.tsx
Fix the height for the legends of the klips-wmts-slider.
> fix legend height

- easy-to-use-api/klips-warning-api/Dockerfile
- easy-to-use-api/klips-warning-api/metro.config.js
- easy-to-use-api/klips-warning-api/package-lock.json
- nginx/default.conf
Needs to use '/' as a location due to the metro bundler.
> fix: fix proxy

- pygeoapi/Dockerfile
- pygeoapi/README.md
- pygeoapi/dev_scripts/lint.sh
- pygeoapi/entry.py
- pygeoapi/processes/algorithms/contour_polygons.py
- pygeoapi/processes/contour_polygons.py
- pygeoapi/processes/contour_polygons_time.py
- pygeoapi/pygeoapi-config.yml
Adds a new process using pygeoapi for generating contour polygons (using the gdal.ContourGenerate()-function) from input raster files.
The interval for which to create the polygons can be set.
> Process for generating contour polygons

- deploy.sh
> fix: fixing deploy script

- .github/workflows/build.yml
> fix: remove dublicated docker build

- easy-to-use-api/klips-dashboard/docs/ogc-services/01-uhi-hi.md
- easy-to-use-api/klips-dashboard/docs/ogc-services/02-temperature-forecast.md
Title says it all
Please review @sdobbert
> fix: fixing some typos

- easy-to-use-api/klips-dashboard/docs/url-generator/03-warning.md
- easy-to-use-api/klips-warning-api/App.tsx
Title says it all.
Please review @sdobbert
> Warning chart

- worker/error-handler/Dockerfile
- worker/rollback-handler/Dockerfile
Title says it all
Please review @sdobbert
> feat: adds healthchecks for the worker

- .env.example
- docker-compose.yml
This fixes the last healthchecks.
Please notice the changes within the .env.examples. We need to adjust these changes on the server also.
> fix: fix healthchecks

- docker-compose.localdev.yml
- docker-compose.yml
- pygeoapi/pygeoapi-config.yml
- Increase upper heap size for geoserver, add adapted values for local dev
- pygeoapi: set log level to error
@sdobbert
> Production settings

- easy-to-use-api/klips-timelapse-video-api/package-lock.json
- easy-to-use-api/klips-timelapse-video-api/package.json
- klips-api/package-lock.json
fix serveral dep conflicts, that occured after latest dependabot update.
fyi @sdobbert
> fix: depencies conflicts

- easy-to-use-api/klips-timelapse-video-api/src/main.ts
- pygeoapi/processes/algorithms/timelapse_video.py
- pygeoapi/processes/timelapse_video.py
Changes pygeoai-process for creating a timelapse-video.
Adds a region variable to select either dresden or langenfeld.
> Add langenfeld to video

- easy-to-use-api/klips-dashboard/docs/ogc-services/03-simulation.md
- easy-to-use-api/klips-dashboard/docs/ogc-services/04-summer.md
> feat: add new demos to dashboard

- demonstrator-ogc-services/klips-wmts-demo/src/App.tsx
- demonstrator-ogc-services/klips-wmts-demo/src/components/BasicTimeSlider/index.tsx
Changes maximum value for time slider from 48 to 47 to match the data.
> fix: max value for time slider

- deploy.sh
> add workers to deploy.sh

- docker-compose.yml
Adds a healthcheck to the worker "geoserver-create-and-apply-sld"
> add healthcheck for sld worker

- easy-to-use-api/klips-warning-api/App.tsx
Makes image size of traffic-light-widget dynamic (e.g. for use in an iframe).
> dynamic image size

- demonstrator-ogc-services/klips-wmts-demo-summer/src/App.less
- demonstrator-ogc-services/klips-wmts-demo-summer/src/App.tsx
- demonstrator-ogc-services/klips-wmts-demo-summer/src/components/BasicLayerSelector/index.less
- easy-to-use-api/klips-dashboard/docs/ogc-services/01-uhi-hi.md
- easy-to-use-api/klips-dashboard/docs/ogc-services/02-temperature-forecast.md
- easy-to-use-api/klips-dashboard/docs/ogc-services/03-simulation.md
- easy-to-use-api/klips-dashboard/docs/ogc-services/04-summer.md
- Edit styling for demonstrator of summer example to match the other examples
- Fix iframe size in Dashboard
> demonstrator styling

- docker-compose.localdev.yml
- docker-compose.yml
- klips-api/src/converter.ts
- pygeoapi/processes/algorithms/contour_polygons.py
- pygeoapi/pygeoapi-config.yml
Adjusts the process for creating contour polygons from incoming tiffs.
Also adds framework for creating a worker to publish the polygons to the database: https://github.com/klips-project/rabbitmq-worker/pull/203
> Polygon process

- docker-compose.localdev.yml
- docker-compose.yml
- klips-api/src/converter.ts
Adds new workers to docker setup.
See https://github.com/klips-project/rabbitmq-worker/pull/212 and https://github.com/klips-project/rabbitmq-worker/pull/211
> add new workers

- klips-api/src/converter.ts
> fix input for reclassify-geotiff worker

- klips-api/src/converter.ts
Change input-Filepath for create-contour worker.
> fix: change input for contour worker

- easy-to-use-api/klips-timelapse-video-api/package-lock.json
- easy-to-use-api/klips-timelapse-video-api/package.json
Fix conflicting peer dependency: @typescript-eslint/eslint-plugin in timelapse-video-api.
> fix: conflicting dependency

- klips-api/src/converter.ts
Adds a new job to the workflow for publishing reclassified geotiffs on the geoserver.
> Job for publishing reclassified geotiffs on geoserver

- docker-compose.yml
Adds port to postgres docker image.
> Add port to postgres docker image

- docker-compose.yml
Remove port for postgres database.
> Fix: remove port for postgres

- klips-api/src/converter.ts
Url needed to be adjusted due to a 'http'-check within the worker
> fix: fixing url
